### ISSUE TITLE
Add full instructions to deploy and see it work

### ISSUE THREAD

**Issue by fulldecent** [fulldecent/aion-aip040#24]
# Source

https://github.com/aionnetwork/AIP/issues/40

# Success metric

> Reference implementation and documentation is entirely usable (results in successful compile, testing and deployment, and usage) for one (1) human test subject that understands blockchain concepts but has no experience with Aion or Java or access to experts.

# Work plan

- [ ] Add screenshot to readme that could only be achieved by successfully creating a wallet, deploying this contract, plus any other required functionality (recommend to mint one token for self and confirm token is owned by self)
- [ ] Add instructions to readme so that Will's dad can follow them. FYI: Will's dad recently stopped using all capital letters when typing emails.
  - It will be unacceptable for the instructions to reference other URLs (i.e. "go follow instruction at OTHER_PAGE") unless that other page has your personal mobile number at the top of the page
- [ ] For all instructions added or best practices cited, also add a reference to the where that instruction or best practice originated into the references section in the readme
- [ ] PLEASE fully test the instructions on your machine before proceeding to the next step
- [ ] PLEASE have your friend fully test the instructions before proceeding to the next step
- [ ] Bill will test the instructions and provide a video artifact

P.S. Just so you know, Bill has successfully followed similar instructions for deploying, and writing a dApp against an NFT contract on Ethereum Ropsten and using it in the web browser at the DLT Education event in New York in 2018.
